services:
  app:
    build:
      context: docker
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
    ports:
      - 8080:80

  chromadb:
    image: chromadb/chroma:latest
    volumes:
      - ./chromadb:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma # this is the default path, change it as needed
      - ANONYMIZED_TELEMETRY=FALSE
