chatbot:
    path: '/'
    controller: 'Symfony\Bundle\FrameworkBundle\Controller\TemplateController'
    defaults:
        template:  'index.html.twig'

youtube:
    path: '/youtube'
    controller: 'Symfony\Bundle\FrameworkBundle\Controller\TemplateController'
    defaults:
        template:  'youtube.html.twig'

wikipedia:
    path: '/wikipedia'
    controller: 'Symfony\Bundle\FrameworkBundle\Controller\TemplateController'
    defaults:
        template:  'wikipedia.html.twig'
