# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    env(CHROMADB_HOST): 'chromadb'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            string $openAiApiKey: '%env(OPENAI_API_KEY)%'
            #string $programFile: '%kernel.project_dir%/wsc-program.txt'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

when@test:
    services:
        Symfony\Component\HttpClient\MockHttpClient:
            factory: ['App\Tests\HttpClientFactory', 'createMock']

        TraceableHttpClient:
            class: Symfony\Component\HttpClient\TraceableHttpClient
            decorates: Symfony\Contracts\HttpClient\HttpClientInterface
            arguments: ['@TraceableHttpClient.inner']

        Symfony\Contracts\HttpClient\HttpClientInterface: '@Symfony\Component\HttpClient\MockHttpClient'
